site_name: Test 2 Code LLM
site_description: Beautiful documentation powered by Material Design
site_author: Filippo Gurioli
strict: true
repo_url: https://github.com/FilippoGurioli/test-2-code-llm
repo_name: FilippoGurioli/test-2-code-llm

theme:
  name: material
  language: en

  icon:
    repo: material/github
    logo: material/code-braces

  favicon: https://raw.githubusercontent.com/microsoft/fluentui-emoji/main/assets/Brain/3D/brain_3d.png

  features:
    # Navigation enhancements
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - navigation.top
    - navigation.footer

    # Table of contents
    - toc.follow
    - toc.integrate

    # Search enhancements
    - search.suggest
    - search.highlight
    - search.share

    # Content features
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.tooltips
    - content.tabs.link

    # Header enhancements
    - header.autohide
    - announce.dismiss

  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  font:
    text: Inter
    code: JetBrains Mono

extra_css:
  - assets/extra.css

extra_javascript:
  - assets/config.js

extra:
  homepage: https://filippogurioli.github.io/test-2-code-llm/
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/FilippoGurioli
      name: GitHub Profile
  generator: false

  # Status badges and version info
  version:
    provider: mike
    default: latest

plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
      lang: en
  - awesome-nav

markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - mdx_truly_sane_lists
  - toc:
      permalink: true
      title: On this page
      permalink_title: Anchor link to this section

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      use_pygments: true
      auto_title: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.blocks.tab:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.critic:
      mode: view
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: FilippoGurioli
      repo: test-2-code-llm
