class TestValidationObserver:
    def on_test_validation_start(model_name: str, test_suite: str) -> None: ...

    def on_test_validation_end(is_failed: bool) -> None: ...

    def on_test_metrics_measured(test_pass_rate: float, coverage: float) -> None: ...
