nav:
  - Home: index.md
  - Introduction: introduction.md
  - Requirements: requirements.md
  - Architecture: architecture.md
  - Design: design.md
  - Implementation: implementation.md
  - Experiments: experiments.md
  - Results: results.md
  - Appendices:
      - Class Diagram: appendices/class-diagram.md
      - Audit and Future Work: appendices/audit.md
