name: Update Dependencies

on:
  schedule:
    # Run weekly on Mondays at 9 AM UTC
    - cron: "0 9 * * 1"
  workflow_dispatch:

jobs:
  update-dependencies:
    name: Update Dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install pip-tools
        run: |
          python -m pip install --upgrade pip
          pip install pip-tools

      - name: Update pre-commit hooks
        run: |
          pip install pre-commit
          pre-commit autoupdate

      - uses: pyupio/safety-action@v1
        with:
          api-key: ${{ secrets.SAFETY_API_KEY }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update dependencies and pre-commit hooks"
          title: "chore: weekly dependency updates"
          body: |
            ## Automated Dependency Updates

            This PR contains automated updates for:
            - Pre-commit hook versions
            - Security vulnerability checks

            Please review the changes and run tests before merging.

            Generated by GitHub Actions.
          branch: chore/update-dependencies
          delete-branch: true
          draft: false
